import * as pulumi from '@pulumi/pulumi';
import './github';
import './google/artifact-registry';
import './google/project';
import './google/dns';
import './google/identity-pool';
import './google/iam';
// import './kubernetes/ingress-controller';
// import './kubernetes/postgres-operator';
import './repositories-with-containers';
import './tabetalt-main';
import * as config from './config';
import * as artifactRegistry from './google/artifact-registry';
import { zone } from './google/dns/zone';
// import { cluster } from './google/gke';
// import { ipAddress } from './google/ip-address';

// export const kubeconfig = pulumi.secret(cluster.getKubeconfig());
export const rootDomain = config.rootDomain;
export const artifactRepoUrl = artifactRegistry.artifactRepoUrl;
export const zoneName = zone.name;
// export const ingressIpAddress = ipAddress.address;
