name: Update Tag
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Which tag
        required: true
      service:
        description: Which service
        required: true
  repository_dispatch:
    types: [update-tag]
jobs:
  update-app-tag:
    name: Update app tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod] # If we have more environments, add them here
    steps:
      - uses: actions/checkout@v3

      - uses: cobraz/setup-inputs@v1
        id: inputs

      - run: echo ${{ steps.inputs.outputs.payload }}

      - name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider:
            ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - uses: cobraz/pulumi-config@v2
        id: config
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          stack-name: app-${{ matrix.env }}
          key: ${{ steps.inputs.outputs.service }}:tag
          value: ${{ steps.inputs.outputs.tag }}
          work-dir: stacks/app

      - uses: cobraz/get-commit-changelog@v1
        if: ${{ steps.config.outputs.key }}
        id: changelog
        with:
          base: ${{ fromJson(steps.config.outputs.key).value }}
          head: ${{ steps.inputs.outputs.tag }}
          repository: tabetalt/${{ steps.inputs.outputs.service }}
          token: ${{ secrets.PAYTRON_GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAYTRON_GITHUB_TOKEN }}
          commit-message:
            bump ${{ steps.inputs.outputs.service }} to ${{
            steps.inputs.outputs.tag }} on ${{ matrix.env }}
          branch: bump-tag-${{ steps.inputs.outputs.service }}-${{ matrix.env }}
          title:
            'chore: bump ${{ steps.inputs.outputs.service }} tag to `${{
            steps.inputs.outputs.tag }}` on ${{ matrix.env }}'
          body: |
            Automated tag change on ${{ matrix.env }}. 🎉

            ${{ steps.changelog.outputs.changelog }}
